version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Bot/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "nuget"
    directory: "/Tests/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
