name: Tets and publish to Codecov.

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Build with dotnet
      run: dotnet build
    - name: Run tests with coverage
      run: dotnet test --no-build --collect:"XPlat Code Coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
      with:
        reports: '*Test*/TestResults/*/coverage.cobertura.xml'
        targetdir: 'CoverageReports'
        reporttypes: 'HtmlInline;Cobertura'
        verbosity: 'Verbose'
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReports        
        path: CoverageReports
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: CoverageReports/Cobertura.xml 
        dry_run: false
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
 